name: GitHub Release
on:
  push:
    tags:
      - '*'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "README.md"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}