name: Release
on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - 'release/**'
      - main

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Run tests
        run: ./mvnw clean verify

      - name: Configure Git
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'filipowm@users.noreply.github.com'

      - name: Release
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.SONATYPE_USERNAME }}
          nexus_password: ${{ secrets.SONATYPE_PASSOWRD }}
          maven_profiles: release
          maven_goals_phases: release:clean release:prepare # release:perform
          maven_args: --batch-mode

