name: Release
on:
  pull_request:
    branches:
      - main

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'release') }}
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'release') }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Configure Git
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'release@users.noreply.github.com'
          git fetch
          git checkout "$(echo ${GITHUB_HEAD_REF})"

      - name: Release to Maven Central
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.SONATYPE_USERNAME }}
          nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
          maven_profiles: release
          maven_goals_phases: release:clean release:prepare release:perform
          maven_args: --batch-mode